### ISSUE TITLE
Support for Postgres Sequences

### ISSUE THREAD

**Issue by beanieboi** [SchemaPlus/schema_plus#146]
In Postgres you can define you custom sequences.
it would be awesome to define them with `schema_plus`

here is an example how we use it in our migration right now.

```
execute "CREATE SEQUENCE invoice_number_seq OWNED BY invoices.invoice_number INCREMENT BY 1 START WITH 10000"
```

```
execute "ALTER TABLE invoices ALTER COLUMN invoice_number SET DEFAULT nextval('invoice_number_seq')"
```

**Comment by zedalaye** [comment]
+1 (can we vote for features ?)

**Comment by ronen** [comment]
@zedalaye sure you can vote -- but I'm afraid it won't do much good unless you can also vote in a few extra hours a day or days a week.

I'd be happy to accept a PR.   But I'm unlikely to add any new features myself.  (Unless I happen to need them for one of my day jobs :)
