### ISSUE TITLE
Bug in README about enums

### ISSUE THREAD

**Issue by zedalaye** [SchemaPlus/schema_plus#176]
In readme, it's said one can create enums using :

```create_enum :name, :value1, :value2...```

Given https://github.com/lomba/schema_plus/blob/master/lib/schema_plus/active_record/connection_adapters/postgresql_adapter.rb#L339

The ```sub``` function is not available for symbols (Ruby 2.1.3). That means that enums must be created using strings :

```create_enum :name, 'value1', 'value2', ... ```

Is this as designed ?

**Comment by ronen** [comment]
@zedalaye Thanks for the report and sorry for the very slow response.

This is fixed in schema_plus 2.0; or rather, in the new [schema_plus_enums](https://github.com/SchemaPlus/schema_plus_enums) gem which is included by schema_plus 2.0
