### ISSUE TITLE
Default value on Postgres' JSON column is ignored when loading the schema

### ISSUE THREAD

**Issue by thmzlt** [SchemaPlus/schema_plus#195]
Using Postgres' JSON columns with default values together with `schema_plus` will render an ActiveRecord schema unstable. Apparently, the hash-based syntax used by `schema_plus` used to assign defaults to values and expressions doesn't work when the default value is a JSON-ish value (i.e. a Ruby hash or a string-encoded JSON object).

To demonstrate the bug, I created a [sample Rails application](https://github.com/thmzlt/test_app) using `rails` (4.1.8), `pg` (latest at 0.17.1) and `schema_plus` (latest at 1.8.2). I also have Postgres installed on OS X 10.9 via homebrew at version 9.3.5. To reproduce the bug, clone the app, bundle install the gems and follow these steps:

- 1. Run the sole migration starting with an empty database. (I used `rake db:drop db:create db:migrate`.) That should result in the following `db/schema.rb`:

```ruby
ActiveRecord::Schema.define(version: 20150113222115) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "things", force: true do |t|
    t.string  "name",                    null: false
    t.integer "level",    default: 1500, null: false
    t.json    "metadata", default: {},   null: false
  end

end
```

- 2. Now, load the schema generated from the previous step and dump it back to the file. (I used `rake db:schema:load db:schema:dump`.) That should result in the following `db/schema.rb`:

```ruby
ActiveRecord::Schema.define(version: 20150113222115) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "things", force: true do |t|
    t.string  "name",                    null: false
    t.integer "level",    default: 1500, null: false
    t.json    "metadata",                null: false
  end

end
```

As you can see, the schema doesn't preserve the default value of the `metadata` column after the dump. On the test app, there is a branch named `vanilla-ar` where `schema_plus` has been extracted from the app, and you can follow the same steps without causing the schema change after the dump.

**Comment by fj** [comment]
I have this issue as well.

**Comment by ronen** [comment]
Thanks for the detailed bug report.  The problem was due to schema_plus's syntax that supports `default: { expr: '<...an expression...>' }` or `default: { value: <defvalue> }`; it was ignoring any other hash.

**Comment by ronen** [comment]
schema_plus 1.8.4 is now released with this fixed.

**Comment by fj** [comment]
Thanks @ronen!
