### ISSUE TITLE
With Rails 4.2 dropping option array: true

### ISSUE THREAD

**Issue by ondrejbartas** [SchemaPlus/schema_plus#199]
Hello 
I upgraded rails from 4.1.5 to 4.2 and then upgraded schema plus to 1.8.5 from version 1.7.0 which was working perfectly fine (befor rails upgrade).

I have migration:

```ruby
# db/migrations/XXX.rb
add_column :users, :notifications, :text, array: true, default: []
```

which currently products this shema:
```ruby
# db/schema.rb
create_table "users", force: :cascade do |t|
  t.text     "notifications", default: []
end
```

but it should look like:

```ruby
# db/schema.rb
create_table "users", force: :cascade do |t|
  t.text     "notifications", default: [], array: true
end
```

Do you have any idea why it is dropping this option?

I tried to get this working with version 1.8.1, 1.8.0, 2.0.0.pre.1

**Comment by ronen** [comment]
@ondrejbartas thanks for the bug report.  Confirmed it's a problem with schema_plus's support of Rails 4.2.  Sorry, I don't have a workaround; I'll try to get a fix in ASAP.

**Comment by ondrejbartas** [comment]
@ronen Thank you very much for fast response. I used branch 1.x in Gemfile and rebuilded schema.db from scratch and it is working now perfectly.

Best

**Comment by ronen** [comment]
@ondrejbartas pretty quick on your part too -- I was just about to ask you to test out the 1.x branch :)  Thanks for verifying it works, I've now released 1.8.6  with this fixed.

But you said you had the same problem with 2.0.0.pre1?  Any chance you could try again and confirm that it fails?  I easily reproduced the problem in the 1.x branch, but I couldn't get it to fail with 2.0.0.pre1

**Comment by ondrejbartas** [comment]
@ronen 
Installed 1.8.6 and working.
Insalled 2.0.0.pre1 - migration went well until 
```
rake aborted!
Don't know how to build task 'schema_monkey:load'
```

So I dont know result because schema wasn't dumped :cry:

**Comment by ronen** [comment]
Aha!  That's a different problem with 2.0.0.pre1 that I just reproduced -- it can't do migrations at all.  D'oh!  I'll look into it.  Thanks for trying it out.

**Comment by ondrejbartas** [comment]
No problem @ronen  any other time you would like to break code, just give me a call :wink: 

Have a resting night :sleeping:

**Comment by ronen** [comment]
>  any other time you would like to break code, just give me a call :wink:

:laughing:   

I fixed the `rake aborted / Don't know how to build task 'schema_monkey:load'` error.  If you want to see what else you can break (in the morning), you can try 2.0.0.pre1 again -- but first bundle update to get the fixed [schema_monkey](https://github.com/SchemaPlus/schema_monkey).

Good night
