### ISSUE TITLE
Would it be OK to for schema_plus 2.0 to drop support for ruby 1.9.3?

### ISSUE THREAD

**Issue by ronen** [SchemaPlus/schema_plus#205]
Hi all,

Opinion poll....

You may know, ruby 2.0 introduced [`Module#prepend`](http://www.ruby-doc.org/core-2.2.0/Module.html#method-i-prepend) which can be used instead of `Module#include`; doing so would replace a lot of ugly uses of `alias_method_chain` in the SchemaPlus family with `super` (see e.g. [this blog post](http://dev.af83.com/2012/10/19/ruby-2-0-module-prepend.html)) -- which is cleaner and safer.   It'd be awfully nice to take advantage of that.

But rails 4.2 officially supports ruby 1.9.3.

So what do you think: Would it be OK to for schema_plus 2.0 to drop support for ruby < 2.0, just like it drops support for activerecord < 4.2?

[Opinions welcome from anyone;  but tagging people who've recently contributed in case you're not watching: @fj, @tovodeverett, @lowjoel, @donv, @mikeauclair, @konjoot, @ondrejbartas, @boone, @robertomiranda , @thmzlt, @dimonzozo, @methodmissing -- thanks!]

**Comment by ondrejbartas** [comment]
Hi,

my opinion is that using older ruby with newest rails is very bad idea. There is no point to use it.

So drop support for ruby 1.9.3.

**Comment by lowjoel** [comment]
Agree with @ondrejbartas. You might want to take the opportunity to restrict v2 to be used only with 2.1 (2.2 isn't really widespread yet)

**Comment by dimonzozo** [comment]
Hi, I think it is totally ok to drop 1.9.3.

Rails 5 is coming this year an it will require ruby 2.2+.

**Comment by ondrejbartas** [comment]
Second thing for dropping is that upgrade from 1.9.3 to 2.0 is without any troubles and you do not need to change any line of code to get it working.

**Comment by ronen** [comment]
Wow, quick response and unanimous so far!   Thanks.

I wonder if folks on the other side of the world will have anything different to say, when they wake up... :)

**Comment by fj** [comment]
Yes, I haven't used 1.9.x for a long time (the main blocker for a while was no MRI debugger in 2.x, but that was solved a while ago).

**Comment by tovodeverett** [comment]
I'm already on 2.2, so it's not a problem for me.  Since `schema_plus` 1.8.4 supports Rails 4.2, you wouldn't be cutting off support for 1.9.3 quite yet.  Also, Ruby 1.9.3 goes EOL in 20 days (https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/, reinforced in https://www.ruby-lang.org/en/news/2014/11/13/ruby-1-9-3-p551-is-released/), at which point security fixes will no longer be available from official sources.

**Comment by ronen** [comment]
Lots of good arguments -- and Ruby 1.9.3 going EOL shortly is the clincher!

OK, will drop support for 1.9.3 .   `prepend` (and keyword args), here I come... :)

Thanks everyone.
