### ISSUE TITLE
`algorithm: :concurrently` is not respected in Rails 4.2

### ISSUE THREAD

**Issue by ankane** [SchemaPlus/schema_plus#209]
Hey, thanks for the great work on this gem.  SchemaPlus 1.8.7 with Rails 4.2.0 silently ignores `algorithm: :concurrently`.  This has pretty bad consequences, as indexes you expect to be created concurrently lock tables.

**Comment by ronen** [comment]
@ankane Thanks for the bug report.  Will try to look into this as soon as I can.

**Comment by ronen** [comment]
@ankane I've released v1.8.8 with this bug fixed.

**Comment by ankane** [comment]
Great, thanks for the quick fix @ronen!
