### ISSUE TITLE
Foreign Keys Incompatible with ActiveRecord 4.2.1 

### ISSUE THREAD

**Issue by sunderwood** [SchemaPlus/schema_plus#210]
I just updated my Rails version to 4.2.1 and found an error with creating foreign keys on a table. The migration works with Rails 4.2.0.

I have a User model and a Subscription Levels model. Here is the Subscription Model Migration:

```
def change
    create_table :subscriptions do |t|
      t.integer :user_id
      t.integer :subscription_level_id

      t.timestamps
    end
end
```

Here is the error: 

```
wrong number of arguments (4 for 1..2)
/usr/local/rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:290:in `foreign_key'
/usr/local/rvm/gems/ruby-2.2.0/gems/schema_plus-1.8.7/lib/schema_plus/active_record/connection_adapters/table_definition.rb:171:in `add_foreign_key'
/usr/local/rvm/gems/ruby-2.2.0/gems/schema_plus-1.8.7/lib/schema_plus/active_record/column_options_handler.rb:44:in `schema_plus_handle_column_options'
```

Note how the backtrace goes from a function in the schema_plus library to a function in the ActiveRecord library. 

I did a quick comparison for the ActiveRecord file of 4.2.0 and 4.2.1 and found that ActiveRecord has started supporting foreign keys. 

Please fix this quickly.

**Comment by ronen** [comment]
@sunderwood  Thanks for the bug report.  There's no new development in the 1.x branch, which means no support for ActiveRecord > 4.2.0.  I've updated the 1.x branch README to make that clear.

But I have fixed this in schema_plus 2.0.0.pre10, which supports both 4.2.0 and 4.2.1.  I suggest you switch to that.

FYI despite the major version bump, schema_plus 2.0.0 is a drop-in replacement for 1.8.7 except for some deprecation warnings you may encounter.   And despite being in prerelease it's completely usable (the only reason it's still in prerelease is that there's still more feature-gem refactoring to be done before the repo is in the proper state for future maintenance).

And of course let me know if you encounter any issues.
