### ISSUE TITLE
Thread safety problem with schema_plus 2 / Postgres

### ISSUE THREAD

**Issue by robdimarco** [SchemaPlus/schema_plus#211]
We recently upgraded a project to use schema_plus 2. Specifically, our `Gemfile` specified to use `schema_plus_views` version 0.1.0. Upon launching to production, we began to see a litany of strange database issues. They did not occur consistently, but we were seeing 10-20 PG errors a day, usually when site was under load. A sample of the errors included:

* `PG::ProtocolViolation: ERROR: bind message supplies 0 parameters, but prepared statement "" requires 1`
* `PG::UnableToSend: extraneous data in "T" message`
* `PG::UnableToSend: SSL SYSCALL error: Bad address`
* `PG::ConnectionBad: PQsocket() can't get socket descriptor`
* `NoMethodError: undefined method `fields' for nil:NilClass` (occurring in the `exec_query` method)

We use Puma as our server, in multi-worker/multi-threaded environment. It appears that there is some kind non-threadsafe behavior happening where different threads are writing to the database connection at the same time.

## Libraries/Architecture

* [rails](https://github.com/rails/rails) 4.2.0 & 4.2.1
* [puma](http://puma.io/) 2.11.1 using 2 workers per server and 16 threads per worker.
* [PostgreSQL](postgresql.org) 9.3.3 & 9.3.6
* [pg gem](https://bitbucket.org/ged/ruby-pg/wiki/Home) 0.18.1
* Ubuntu 14.04.2 LTS

Upon reverting back to the older version of the gem, the errors disappeared. 

I'm not sure if this is the right place for the issue (maybe schema_plus_core?). I also struggled to reliably reproduce it in a testing environment, so I do not have a good test set to give you that replicates the issue.

**Comment by ronen** [comment]
@robdimarco Oh dear.  Sorry for the trouble and thanks for the bug report.

Looking at the code, I found a likely source of thread unsafety, in the [modware](https://github.com/ronen/modware) gem.  I've fixed it and released version 0.1.1 of that gem.

Of course this is a bit of a shot in the dark.  But would you be willing to try schema_plus_views again, making sure that you're pulling in modware 0.1.1?

**Comment by robdimarco** [comment]
@ronen Thanks for the quick response on it. I might be able to try it tomorrow on a subset of our traffic and see if it holds.

**Comment by ronen** [comment]
@robdirmarco Actually I just saw another possible thread unsafety in modware.  Version 0.1.2 coming soon...

**Comment by ronen** [comment]
@robdimarco OK, modware 0.1.2 is ready.

If you can try it whenever you get a chance, that'd be great.  Thanks for being an (inadvertant) threading guinea pig.

**Comment by robdimarco** [comment]
I just did a bundle update and got modware 0.1.1, did you release 0.1.2? Bundler did not seem to find it.

**Comment by ronen** [comment]
oops, you're right -- pushed to github but didn't release to rubygems.  it's released now.  try again?

**Comment by robdimarco** [comment]
I have not seen any issues, thanks for your help

**Comment by ronen** [comment]
Great!  Thanks for your working through this.
