### ISSUE TITLE
When using add_column foreign key does not use the default_name method

### ISSUE THREAD

**Issue by kushkella** [SchemaPlus/schema_plus#216]
I'm using add_column at several places to add references

```ruby
add_column :activities, :user_id
```

When doing so, the SQL generated by schema_plus is something like:

```
FOREIGN KEY ("user_id") REFERENCES "users" ("id")
```

However when doing the same during table creation, it generates SQL with constraint name:

```
CONSTRAINT fk_activites_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("id")
```

The former SQL forces Postgres to use default name for the constraint which is not same as the default name by SchemaPlus. Previously this was not the case. It would be great if SchemaPlus can generate similar SQL for `add_column` as it does when creating table, since this is a breaking change.

Thanks

**Comment by kushkella** [comment]
I think the solution is to change the `add_foreign_key` method to set default name. Something like this

```ruby
        def add_foreign_key(*args) # (table_name, column, to_table, primary_key, options = {})
          options = args.extract_options!
          case args.length
          when 2
            from_table, to_table = args
          when 4
            ActiveSupport::Deprecation.warn "4-argument form of add_foreign_key is deprecated.  use add_foreign_key(from_table, to_table, options)"
            (from_table, column, to_table, primary_key) = args
            options.merge!(column: column, primary_key: primary_key)
          end

          options = options.dup
          options[:column] ||= foreign_key_column_for(to_table)
          options[:name]   ||= ForeignKeyDefinition.default_name(from_table, options[:column])

          foreign_key_sql = add_foreign_key_sql(from_table, to_table, options)
          execute "ALTER TABLE #{quote_table_name(from_table)} #{foreign_key_sql}"
        end
```

**Comment by ronen** [comment]
@kushkella Yes that looks right.  Care to add a (failing) spec that tests this, then make the above fix?

**Comment by kushkella** [comment]
Sure, will do.
