### ISSUE TITLE
add_foreign_key not compatible with Activerecord version

### ISSUE THREAD

**Issue by AlexCppns** [SchemaPlus/schema_plus#226]
I cannot make it work because of an argument mismatch:
```wrong number of arguments (3 for 4)/usr/local/src/admin/vendor/gem/ruby/1.9.1/gems/schema_plus-0.4.1/lib/schema_plus/active_record/connection_adapters/abstract_adapter.rb:93:in `add_foreign_key'```

**Comment by ronen** [comment]
@AlexCppns from the above error message it seems you're using schema_plus version 0.4.1?  I can't tell which version of ActiveRecord you're trying to use it with -- it worked with ActiveRecord 2.3-3.2.  But in any case version 0.4.1 of schema_plus is too old  to support.

The current version of schema_plus is 2.0.0, which works with ActiveRecord >= 4.2.0
For older versions of ActiveRecord, the latest stable version is 1.8.9; but no new development is going into the 1.x branch, only the occasional (rare) bug fix if it's really critical.

Closing out this issue, but if you're encountering a problem with the current version please do (re)open!
