### ISSUE TITLE
All but the last `t.index` reference for a table are ignored

### ISSUE THREAD

**Issue by fj** [SchemaPlus/schema_plus#227]
Given this schema.rb containing this fragment:

```
  create_table "streams", force: :cascade do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.jsonb    "dependencies",       null: false
    t.index name: "index_first", using: :gin, expression: "(dependencies -> 'one'::text)"
    t.index name: "index_second", using: :gin, expression: "(dependencies -> 'two'::text)"
  end
```

and then running `rake db:drop db:create db:schema:load`, only the second index is created. This is using the schema_plus on `master`, using Padrino.

**Comment by ronen** [comment]
@fj thanks for the bug report -- i reproduced it using rails too.  will take a look

**Comment by ronen** [comment]
Closed in favor of SchemaPlus/schema_plus_pg_indexes#8

**Comment by ronen** [comment]
@fj fixed it [schema_plus_pg_indexes](http://github.com/SchemaPlus/schema_plus_pg_indexes) v0.1.9, which should be pulled in by schema_plus if you bundle update

**Comment by ronen** [comment]
@fj oops committed the version yesterday bump but forgot to do the release.  *now* schema_plus_pg_indexes v0.1.9 is released
