### ISSUE TITLE
Wrong foreign_key format in schema.rb

### ISSUE THREAD

**Issue by sharq1** [SchemaPlus/schema_plus#228]
schema:dump generates this in schema.rb

```
...
t.foreign_key ["conversation_id"], "mailboxer_conversations", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "mb_opt_outs_on_conversations_id"
...
```
which results in `ArgumentError: wrong number of arguments (4 for 1..2)` on schema:load

Migration that it origins from is:
```
add_foreign_key "mailboxer_notifications", "mailboxer_conversations", :name => "notifications_on_conversation_id", :column => "conversation_id"
```

**Comment by ronen** [comment]
@sharq1 thanks for the bug report.  which versions of ActiveRecord and schema_plus family of gems are you using?

**Comment by sharq1** [comment]
schema_plus is at 1.8.9
activerecord is at 4.1.12

**Comment by ronen** [comment]
oh dear....  schema_plus has moved on to 2.* for activerecord 4.2+.   i don't suppose you could upgrade?

i'm happy to accept a PR to fix bugs in the 1.8 branch but not likely to have time to dive into it myself.

**Comment by sharq1** [comment]
I tried that first, but there's too many dependencies in the project.
I achieved what I wanted without schema_plus, so I suppose that noone will fix this and since it's probably just old version problem this can be closed.
Thank you for the fast replies.

**Comment by ronen** [comment]
ok, thanks for accommodating and sorry not to be more helpful.
