### ISSUE TITLE
Support ruby +2.1

### ISSUE THREAD

**Issue by WaKeMaTTa** [SchemaPlus/schema_plus#234]
Hi, ¿Why do you only support ruby 2.1.5?

Thanks for work! :beers:

**Comment by boazy** [comment]
SchemaPlus supports Ruby 2.3.x and probably 2.4.0 and most gems are tested against Ruby 2.3.x. This is just a metagem for compatibility, and it wasn't tested with newer versions yet.

**Comment by boazy** [comment]
@ronen Do you want to update tests for all gems to Ruby 2.4? That might be confusing in the other direction (i.e. people could think that Ruby 2.1 is not supported while it usually is)
